# Celcat bot configuration

# Server root URL
server: <celcat server root URL>

# How many time forward to update (timedelta args)
distance:
  days: 15

# Custom calendar timezone
timezone: null

# Celcat resssource type value
ressource: 103

# Celcat groups to get
groups:
  - <group 1>

# EOF